Development
sdandois/training pull request #1
Opened 2018-10-19 16:19 UTC by sdandois

TODO List
========

Lista de tares que permite agregar, marcar y eliminar tareas

Components
-------------
Header.js : Display tittle
Footer.js : Display button to remove completed
TodoList.js : Container of TodoItems
TodoItem.js : Display the text of a certain todo and show if it is marked as done.
InputTodo.js : Input Text. Add new todo on submit

State
-----
todos: Array of todos
inputText: text on inputTodo component textfield.
nextId: the id of the next todo to be created

Todo format
------------
text
id
done: Flag that is true if completed

Actions
-------
INPUT_CHANGE (text) : change on inputTodo textfield.
ADD_TODO: Adds a new todo to the list
REMOVE_TODO (id): remove todo with the given id
TOGGLE_DONE (id): toogles done (completed) status of a todo
REMOVE_COMPLETED: Remove all done todos (completed).

2018-10-22 19:02 UTC, fbazzana requested changes

2018-10-22 19:02 UTC, fbazzana commented on index.js
> +
Delete this blank lines

2018-10-22 19:02 UTC, fbazzana commented on index.js
> +
Same here, with only one line it's ok.
Also, let spaces in destructuring: `import { AppRegistry } from 'react-native';`

2018-10-22 19:02 UTC, fbazzana commented on src/App.js
> +};
Extract this styles in another file. Also, try to use [StyleSheet](https://facebook.github.io/react-native/docs/stylesheet).

2018-10-22 19:02 UTC, fbazzana commented on src/App.js
> +      </Provider>
Good approach! But, instead of this, you could define a file wrapping this app content, like this:
```
import React from 'react';
import { Provider } from 'react-redux';

import store from './redux/store'; // Check this route

export default function index() {
  return (
    <Provider store={store}>
      <App />
    </Provider>
  );
}
```
Then, in ```index.js``` register this component instead of ```App.js```.

Also, this could be part of another component:
```
<View style={styles.container}>
  <Header />
  <InputTodo />
  <TodoList />
  <Footer />
</View>
```

2018-10-22 19:02 UTC, fbazzana commented on src/App.js
> +      </Provider>
Only as a comment, you could user Header from ```react-navigation```. See [this](https://reactnavigation.org/docs/en/headers.html).

2018-10-22 19:02 UTC, fbazzana commented on src/components/Footer.js
> +const styles = {
extract this styles in another component.

2018-10-22 19:02 UTC, fbazzana commented on src/components/Footer.js
> +    backgroundColor: '#EEE'
Extract colors into a constants file. You could create ```/constants/colors.js``` and put them there.

2018-10-22 19:02 UTC, fbazzana commented on src/components/Footer.js
> +const BUTTON_DELETE_TEXT = 'Remove Completed';
Create a ```constants.js``` file into this folder and define this constant here.

2018-10-22 19:02 UTC, fbazzana commented on src/components/Footer.js
> +export default connect(null , {removeCompleted})( Footer );
Delete this blank spaces in ```( Footer )```.
Also, ```connect``` accepts two functions in his first two parameters, ```mapStateToProps``` and ```mapDispatchToProps```. You could read [this](https://blog.logrocket.com/react-redux-connect-when-and-how-to-use-it-f2a1edab2013) for more information.
Check it out to know how to define this properly!

2018-10-22 19:02 UTC, fbazzana commented on src/components/Header.js
> +const styles = {
Extract this styles into another file.
Try to let a space before each property. I mean, ```height: 60``` instead of ```height:60```.

2018-10-22 19:02 UTC, fbazzana commented on src/App.js
> +export default class App extends Component {
Instead of ```Component```, you could use something else: ```PureComponent```. Check [this](https://codeburst.io/when-to-use-component-or-purecomponent-a60cfad01a81)!

2018-10-22 19:02 UTC, fbazzana commented on src/components/InputTodo.js
> +      <View style = { styles.view } >
Here, be careful with spaces.
Instead of ```<View style = { styles.view } >```, use ```<View style={styles.view}>```.

Same in ```<TextInput ...```

2018-10-22 19:02 UTC, fbazzana commented on src/components/InputTodo.js
> +export default connect( mapStateToProps, { changeInput, addTodo } )( InputTodo );
Check ```mapDispatchToProps``` here.

2018-10-22 19:02 UTC, fbazzana commented on src/components/InputTodo.js
> +const PLACE_HOLDER = 'Enter a item...';
Extract this into a constants file

2018-10-22 19:02 UTC, fbazzana commented on src/components/TodoItem.js
> +  }
You could define this functions as an arrow functions:
```toggleDone = () => this.props.toggleDone(this.props.todo.id);```
```removeTodo = () => this.props.removeTodo(this.props.todo.id);```

2018-10-22 19:02 UTC, fbazzana commented on src/components/TodoItem.js
> +  render () {
Careful with spaces!

2018-10-22 19:02 UTC, fbazzana commented on src/components/TodoItem.js
> +const styles = {
Extract this into a constants file.

2018-10-22 19:02 UTC, fbazzana commented on src/components/TodoItem.js
> +export default connect(null, { toggleDone, removeTodo })( TodoItem );
```mapDispatchToProps```

2018-10-22 19:02 UTC, fbazzana commented on src/components/TodoList.js
> +  }
Define this functions like this:
```renderItem = ({ item }) => <TodoItem todo={item} />;```
```keyExtractor = (item) => item.id.toString();```

2018-10-22 19:02 UTC, fbazzana commented on src/components/TodoList.js
> +export default connect( mapStateToProps )( TodoList );
Extract styles into another file and check spaces!

2018-10-22 19:02 UTC, fbazzana commented on src/components/common/Button.js
> +export { Button };
Same here!

2018-10-22 19:02 UTC, fbazzana commented on src/reducers/index.js
> +
Good! Beware about spaces!

2018-10-22 19:02 UTC, fbazzana commented
@sdandois good work! Check my comments!

2018-10-24 13:27 UTC, sdandois commented on src/App.js
> +      </Provider>
Changes on Navigation Branch.

2018-10-29 15:17 UTC, fbazzana approved these changes

2018-10-30 13:02 UTC, merged